// This file maps static frontend routes to their corresponding documentation page keys.
// It's used by the AppLayout to show the contextual help button.
// In React Native, this would be used by a custom header component to show a help icon.

const pageRoutes = {
	// User Pages
	'Dashboard': 'dashboard',
	'Team': 'team_directory',
	'Chat': 'chat',
	'Lehrgänge': 'lehrgaenge',
	'Veranstaltungen': 'events',
	'Lager': 'storage',
	'Dateien': 'files',
	'Kalender': 'calendar',
	'Feedback': 'feedback',
	'Changelogs': 'changelogs',
	'Profile': 'profile',
	'Settings': 'settings',
	'PasswordChange': 'password_change',
	'Search': 'search_results',
	'HelpList': 'help_list',
	'HelpDetails': 'help_details',
	'Notifications': 'notifications',

	// Admin Pages (by Route Name)
	'AdminDashboard': 'admin_dashboard',
	'AdminUsersIndex': 'admin_users_index',
	'AdminUsers': 'admin_users',
	'AdminRequests': 'admin_requests',
	'AdminTrainingRequests': 'admin_training_requests',
	'AdminAchievements': 'admin_achievements',
	'AdminEventsIndex': 'admin_events_index',
	'AdminEvents': 'admin_events',
	'AdminDebriefingsList': 'admin_debriefings_list',
	'AdminEventRoles': 'admin_event_roles',
	'AdminVenues': 'admin_venues',
	'AdminChecklistTemplates': 'admin_checklist_templates',
	'AdminCoursesIndex': 'admin_courses_index',
	'AdminCourses': 'admin_courses',
	'AdminMatrix': 'admin_matrix',
	'AdminStorageIndex': 'admin_storage_index',
	'AdminStorage': 'admin_storage',
	'AdminKits': 'admin_kits',
	'AdminDefective': 'admin_defective_items',
	'AdminDamageReports': 'admin_damage_reports',
	'AdminContentIndex': 'admin_content_index',
	'AdminAnnouncements': 'admin_announcements',
	'AdminFiles': 'admin_files',
	'AdminFeedback': 'admin_feedback',
	'AdminChangelogs': 'admin_changelogs',
	'AdminDocumentation': 'admin_documentation',
	'AdminNotifications': 'admin_notifications',
	'AdminReportsIndex': 'admin_reports_index',
	'AdminReports': 'admin_reports',
	'AdminLog': 'admin_log',
	'AdminSystemIndex': 'admin_system_index',
	'AdminSystemStatus': 'admin_system',
	'AdminAuthLog': 'admin_auth_log',
	'AdminWiki': 'admin_wiki',
};

export default pageRoutes;