package de.technikteam.config;

import com.google.inject.Scopes;
import com.google.inject.servlet.ServletModule;
import de.technikteam.dao.*;
import de.technikteam.service.*;
import de.technikteam.servlet.*;
import de.technikteam.servlet.admin.*;
import de.technikteam.servlet.admin.action.*;
import de.technikteam.servlet.admin.api.*;
import de.technikteam.servlet.api.*;
import de.technikteam.servlet.api.passkey.*;

public class ServiceModule extends ServletModule {

	@Override
	protected void configureServlets() {
		// --- Bind Services, DAOs, and Actions (Singletons) ---
		bind(ConfigurationService.class).in(Scopes.SINGLETON);
		bind(DatabaseManager.class).in(Scopes.SINGLETON);
		bind(AuthorizationService.class).in(Scopes.SINGLETON);
		bind(AdminLogService.class).in(Scopes.SINGLETON);
		bind(UserService.class).in(Scopes.SINGLETON);
		bind(StorageService.class).in(Scopes.SINGLETON);
		bind(EventService.class).in(Scopes.SINGLETON);
		bind(PasskeyService.class).in(Scopes.SINGLETON);
		bind(SystemInfoService.class).in(Scopes.SINGLETON);
		bind(AchievementService.class).in(Scopes.SINGLETON);
		bind(AdminDashboardService.class).in(Scopes.SINGLETON);

		bind(UserDAO.class).in(Scopes.SINGLETON);
		bind(RoleDAO.class).in(Scopes.SINGLETON);
		bind(PermissionDAO.class).in(Scopes.SINGLETON);
		bind(StorageDAO.class).in(Scopes.SINGLETON);
		bind(StorageLogDAO.class).in(Scopes.SINGLETON);
		bind(EventDAO.class).in(Scopes.SINGLETON);
		bind(EventTaskDAO.class).in(Scopes.SINGLETON);
		bind(EventChatDAO.class).in(Scopes.SINGLETON);
		bind(CourseDAO.class).in(Scopes.SINGLETON);
		bind(MeetingDAO.class).in(Scopes.SINGLETON);
		bind(MeetingAttendanceDAO.class).in(Scopes.SINGLETON);
		bind(UserQualificationsDAO.class).in(Scopes.SINGLETON);
		bind(AchievementDAO.class).in(Scopes.SINGLETON);
		bind(AdminLogDAO.class).in(Scopes.SINGLETON);
		bind(AttachmentDAO.class).in(Scopes.SINGLETON);
		bind(InventoryKitDAO.class).in(Scopes.SINGLETON);
		bind(MaintenanceLogDAO.class).in(Scopes.SINGLETON);
		bind(PasskeyDAO.class).in(Scopes.SINGLETON);
		bind(ProfileChangeRequestDAO.class).in(Scopes.SINGLETON);
		bind(EventFeedbackDAO.class).in(Scopes.SINGLETON);
		bind(EventCustomFieldDAO.class).in(Scopes.SINGLETON);
		bind(FeedbackSubmissionDAO.class).in(Scopes.SINGLETON);
		bind(FileDAO.class).in(Scopes.SINGLETON);
		bind(ReportDAO.class).in(Scopes.SINGLETON);
		bind(StatisticsDAO.class).in(Scopes.SINGLETON);

		bind(CreateUserAction.class).in(Scopes.SINGLETON);
		bind(UpdateUserAction.class).in(Scopes.SINGLETON);
		bind(DeleteUserAction.class).in(Scopes.SINGLETON);
		bind(ResetPasswordAction.class).in(Scopes.SINGLETON);
		bind(UnlockUserAction.class).in(Scopes.SINGLETON);
		bind(ApproveChangeAction.class).in(Scopes.SINGLETON);
		bind(DenyChangeAction.class).in(Scopes.SINGLETON);
		bind(UpdateFeedbackStatusAction.class).in(Scopes.SINGLETON);
		bind(DeleteFeedbackAction.class).in(Scopes.SINGLETON);

		// --- Explicitly bind all Servlets as Singletons before serving them ---
		bind(RootServlet.class).in(Scopes.SINGLETON);
		bind(LoginServlet.class).in(Scopes.SINGLETON);
		bind(LogoutServlet.class).in(Scopes.SINGLETON);
		bind(HomeServlet.class).in(Scopes.SINGLETON);
		bind(ProfileServlet.class).in(Scopes.SINGLETON);
		bind(PasswordServlet.class).in(Scopes.SINGLETON);
		bind(CalendarServlet.class).in(Scopes.SINGLETON);
		bind(IcalServlet.class).in(Scopes.SINGLETON);
		bind(EventServlet.class).in(Scopes.SINGLETON);
		bind(EventDetailsServlet.class).in(Scopes.SINGLETON);
		bind(EventActionServlet.class).in(Scopes.SINGLETON);
		bind(MeetingServlet.class).in(Scopes.SINGLETON);
		bind(MeetingDetailsServlet.class).in(Scopes.SINGLETON);
		bind(MeetingActionServlet.class).in(Scopes.SINGLETON);
		bind(StorageServlet.class).in(Scopes.SINGLETON);
		bind(StorageItemDetailsServlet.class).in(Scopes.SINGLETON);
		bind(StorageItemActionServlet.class).in(Scopes.SINGLETON);
		bind(StorageTransactionServlet.class).in(Scopes.SINGLETON);
		bind(FileServlet.class).in(Scopes.SINGLETON);
		bind(FeedbackServlet.class).in(Scopes.SINGLETON);
		bind(MyFeedbackServlet.class).in(Scopes.SINGLETON);
		bind(PackKitServlet.class).in(Scopes.SINGLETON);
		bind(DownloadServlet.class).in(Scopes.SINGLETON);
		bind(ImageServlet.class).in(Scopes.SINGLETON);
		bind(MarkdownEditorServlet.class).in(Scopes.SINGLETON);
		bind(TaskActionServlet.class).in(Scopes.SINGLETON);
		bind(NotificationServlet.class).in(Scopes.SINGLETON);
		bind(CalendarApiServlet.class).in(Scopes.SINGLETON);
		bind(StorageHistoryApiServlet.class).in(Scopes.SINGLETON);
		bind(UserPreferencesApiServlet.class).in(Scopes.SINGLETON);
		bind(EventCustomFieldsApiServlet.class).in(Scopes.SINGLETON);
		bind(EventChatApiServlet.class).in(Scopes.SINGLETON);
		bind(MarkdownApiServlet.class).in(Scopes.SINGLETON);
		bind(RegistrationStartServlet.class).in(Scopes.SINGLETON);
		bind(RegistrationFinishServlet.class).in(Scopes.SINGLETON);
		bind(AuthenticationStartServlet.class).in(Scopes.SINGLETON);
		bind(AuthenticationFinishServlet.class).in(Scopes.SINGLETON);
		bind(AdminDashboardServlet.class).in(Scopes.SINGLETON);
		bind(AdminUserServlet.class).in(Scopes.SINGLETON);
		bind(AdminEventServlet.class).in(Scopes.SINGLETON);
		bind(AdminCourseServlet.class).in(Scopes.SINGLETON);
		bind(AdminMeetingServlet.class).in(Scopes.SINGLETON);
		bind(AdminAttendanceServlet.class).in(Scopes.SINGLETON);
		bind(MatrixServlet.class).in(Scopes.SINGLETON);
		bind(AdminStorageServlet.class).in(Scopes.SINGLETON);
		bind(AdminDefectServlet.class).in(Scopes.SINGLETON);
		bind(AdminKitServlet.class).in(Scopes.SINGLETON);
		bind(AdminFileManagementServlet.class).in(Scopes.SINGLETON);
		bind(AdminFileServlet.class).in(Scopes.SINGLETON);
		bind(AdminFileCategoryServlet.class).in(Scopes.SINGLETON);
		bind(AdminLogServlet.class).in(Scopes.SINGLETON);
		bind(AdminReportServlet.class).in(Scopes.SINGLETON);
		bind(AdminSystemServlet.class).in(Scopes.SINGLETON);
		bind(AdminAchievementServlet.class).in(Scopes.SINGLETON);
		bind(AdminChangeRequestServlet.class).in(Scopes.SINGLETON);
		bind(AdminFeedbackServlet.class).in(Scopes.SINGLETON);
		bind(AdminDashboardApiServlet.class).in(Scopes.SINGLETON);
		bind(SystemStatsApiServlet.class).in(Scopes.SINGLETON);
		bind(CrewFinderApiServlet.class).in(Scopes.SINGLETON);
		bind(FrontControllerServlet.class).in(Scopes.SINGLETON);

		// --- Explicitly Map all URL Patterns to their Servlets ---
		serve("").with(RootServlet.class);
		serve("/login").with(LoginServlet.class);
		serve("/logout").with(LogoutServlet.class);
		serve("/home").with(HomeServlet.class);
		serve("/profil").with(ProfileServlet.class);
		serve("/passwort").with(PasswordServlet.class);
		serve("/kalender").with(CalendarServlet.class);
		serve("/calendar.ics").with(IcalServlet.class);
		serve("/veranstaltungen").with(EventServlet.class);
		serve("/veranstaltungen/details").with(EventDetailsServlet.class);
		serve("/event-action").with(EventActionServlet.class);
		serve("/lehrgaenge").with(MeetingServlet.class);
		serve("/meetingDetails").with(MeetingDetailsServlet.class);
		serve("/meeting-action").with(MeetingActionServlet.class);
		serve("/lager").with(StorageServlet.class);
		serve("/lager/details").with(StorageItemDetailsServlet.class);
		serve("/lager/aktionen").with(StorageItemActionServlet.class);
		serve("/lager/transaktion").with(StorageTransactionServlet.class);
		serve("/dateien").with(FileServlet.class);
		serve("/feedback").with(FeedbackServlet.class);
		serve("/my-feedback").with(MyFeedbackServlet.class);
		serve("/pack-kit").with(PackKitServlet.class);
		serve("/download").with(DownloadServlet.class);
		serve("/image").with(ImageServlet.class);
		serve("/editor").with(MarkdownEditorServlet.class);
		serve("/task-action").with(TaskActionServlet.class);
		serve("/notifications").with(NotificationServlet.class);
		serve("/api/calendar/entries").with(CalendarApiServlet.class);
		serve("/api/storage-history").with(StorageHistoryApiServlet.class);
		serve("/api/user/preferences").with(UserPreferencesApiServlet.class);
		serve("/api/public/event-custom-fields").with(EventCustomFieldsApiServlet.class);
		serve("/api/event-chat").with(EventChatApiServlet.class);
		serve("/api/save-markdown").with(MarkdownApiServlet.class);
		serve("/api/auth/passkey/register/start").with(RegistrationStartServlet.class);
		serve("/api/auth/passkey/register/finish").with(RegistrationFinishServlet.class);
		serve("/api/auth/passkey/login/start").with(AuthenticationStartServlet.class);
		serve("/api/auth/passkey/login/finish").with(AuthenticationFinishServlet.class);
		serve("/admin/dashboard").with(AdminDashboardServlet.class);
		serve("/admin/mitglieder").with(AdminUserServlet.class);
		serve("/admin/veranstaltungen").with(AdminEventServlet.class);
		serve("/admin/lehrgaenge").with(AdminCourseServlet.class);
		serve("/admin/meetings").with(AdminMeetingServlet.class);
		serve("/admin/teilnahme").with(AdminAttendanceServlet.class);
		serve("/admin/matrix").with(MatrixServlet.class);
		serve("/admin/lager").with(AdminStorageServlet.class);
		serve("/admin/defekte").with(AdminDefectServlet.class);
		serve("/admin/kits").with(AdminKitServlet.class);
		serve("/admin/dateien").with(AdminFileManagementServlet.class);
		serve("/admin/uploadFile").with(AdminFileServlet.class);
		serve("/admin/dateien/kategorien/*").with(AdminFileCategoryServlet.class);
		serve("/admin/log").with(AdminLogServlet.class);
		serve("/admin/berichte").with(AdminReportServlet.class);
		serve("/admin/system").with(AdminSystemServlet.class);
		serve("/admin/achievements").with(AdminAchievementServlet.class);
		serve("/admin/requests").with(AdminChangeRequestServlet.class);
		serve("/admin/feedback").with(AdminFeedbackServlet.class);
		serve("/api/admin/dashboard-data").with(AdminDashboardApiServlet.class);
		serve("/api/admin/system-stats").with(SystemStatsApiServlet.class);
		serve("/api/admin/crew-finder").with(CrewFinderApiServlet.class);
		serve("/admin/action/*").with(FrontControllerServlet.class);
	}
}