// This file centralizes all permission key constants used throughout the frontend.
// It mirrors the `de.technikteam.config.Permissions` class on the backend.
export const Permissions = {
  // GLOBAL
  ACCESS_ADMIN_PANEL: "ACCESS_ADMIN_PANEL",

  // USER MANAGEMENT
  USER_CREATE: "USER_CREATE",
  USER_READ: "USER_READ",
  USER_UPDATE: "USER_UPDATE",
  USER_DELETE: "USER_DELETE",
  USER_PASSWORD_RESET: "USER_PASSWORD_RESET",
  PERMISSION_MANAGE: "PERMISSION_MANAGE",

  // EVENT MANAGEMENT
  EVENT_CREATE: "EVENT_CREATE",
  EVENT_READ: "EVENT_READ",
  EVENT_UPDATE: "EVENT_UPDATE",
  EVENT_DELETE: "EVENT_DELETE",
  EVENT_MANAGE_ASSIGNMENTS: "EVENT_MANAGE_ASSIGNMENTS",
  EVENT_MANAGE_TASKS: "EVENT_MANAGE_TASKS",
  EVENT_DEBRIEFING_VIEW: "EVENT_DEBRIEFING_VIEW",
  EVENT_DEBRIEFING_MANAGE: "EVENT_DEBRIEFING_MANAGE",
  AVAILABILITY_MANAGE: "AVAILABILITY_MANAGE",

  // COURSE & MEETING MANAGEMENT
  COURSE_CREATE: "COURSE_CREATE",
  COURSE_READ: "COURSE_READ",
  COURSE_UPDATE: "COURSE_UPDATE",
  COURSE_DELETE: "COURSE_DELETE",

  // STORAGE & INVENTORY
  STORAGE_CREATE: "STORAGE_CREATE",
  STORAGE_READ: "STORAGE_READ",
  STORAGE_UPDATE: "STORAGE_UPDATE",
  STORAGE_DELETE: "STORAGE_DELETE",
  DAMAGE_REPORT_MANAGE: "DAMAGE_REPORT_MANAGE",

  // KIT MANAGEMENT
  KIT_CREATE: "KIT_CREATE",
  KIT_READ: "KIT_READ",
  KIT_UPDATE: "KIT_UPDATE",
  KIT_DELETE: "KIT_DELETE",

  // QUALIFICATIONS
  QUALIFICATION_READ: "QUALIFICATION_READ",
  QUALIFICATION_UPDATE: "QUALIFICATION_UPDATE",

  // FILE MANAGEMENT
  FILE_CREATE: "FILE_CREATE",
  FILE_READ: "FILE_READ",
  FILE_UPDATE: "FILE_UPDATE",
  FILE_DELETE: "FILE_DELETE",
  FILE_MANAGE: "FILE_MANAGE",

  // SYSTEM & REPORTING
  LOG_READ: "LOG_READ",
  REPORT_READ: "REPORT_READ",
  SYSTEM_READ: "SYSTEM_READ",
  LOG_REVOKE: "LOG_REVOKE",

  // ACHIEVEMENTS
  ACHIEVEMENT_CREATE: "ACHIEVEMENT_CREATE",
  ACHIEVEMENT_UPDATE: "ACHIEVEMENT_UPDATE",
  ACHIEVEMENT_DELETE: "ACHIEVEMENT_DELETE",
  ACHIEVEMENT_VIEW: "ACHIEVEMENT_VIEW",

  // NOTIFICATIONS
  NOTIFICATION_SEND: "NOTIFICATION_SEND",

  // DOCUMENTATION
  DOCUMENTATION_MANAGE: "DOCUMENTATION_MANAGE",

  // POLLS
  POLL_MANAGE: "POLL_MANAGE",

  // NAVIGATION-SPECIFIC
  ADMIN_DASHBOARD_ACCESS: "ADMIN_DASHBOARD_ACCESS",
};